# Generated by Django 2.0.2 on 2018-02-09 16:34

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='关于作者正文')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '关于作者',
                'ordering': ('created_time',),
                'verbose_name': '关于作者',
            },
        ),
        migrations.CreateModel(
            name='AboutSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='关于本站正文')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '关于本站',
                'ordering': ('created_time',),
                'verbose_name': '关于本站',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='添加分类')),
            ],
            options={
                'verbose_name_plural': '分类',
                'verbose_name': '分类',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reader_name', models.CharField(max_length=80, null=True, verbose_name='读者名字')),
                ('body', models.TextField(verbose_name='评论内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('active', models.BooleanField(default=True, verbose_name='是否可用')),
            ],
            options={
                'verbose_name_plural': '评论',
                'ordering': ('created_time',),
                'verbose_name': '评论',
            },
        ),
        migrations.CreateModel(
            name='FriendWeb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_pic', models.ImageField(help_text='请上传120*40像素logo', upload_to='photos/friend_log/%Y/%m/%d/', verbose_name='友情链接logo图片')),
                ('friend_web_name', models.CharField(max_length=80, verbose_name='网站名字')),
                ('web_address', models.CharField(max_length=100, verbose_name='网址')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': '友情链接',
                'ordering': ('created',),
                'verbose_name': '友情链接',
            },
        ),
        migrations.CreateModel(
            name='MessageBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, null=True, verbose_name='昵称')),
                ('body', models.TextField(verbose_name='欢迎留言')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': '留言',
                'ordering': ('-created',),
                'verbose_name': '留言',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='文章标题')),
                ('post_thumb', models.ImageField(blank=True, help_text='请上传186*90像素图片，用于本文章缩略图', null=True, upload_to='photos/thumbs/%Y/%m/%d/', verbose_name='文章缩略图')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='正文')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10, verbose_name='文章状态')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='默认阅读数量')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mysite_posts', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Category', verbose_name='类别')),
            ],
            options={
                'verbose_name_plural': '文章',
                'ordering': ('-created_time',),
                'verbose_name': '文章',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='添加标签项')),
            ],
            options={
                'verbose_name_plural': '标签',
                'verbose_name': '标签',
            },
        ),
        migrations.CreateModel(
            name='WebSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_name', models.CharField(max_length=250, verbose_name='网站名称')),
                ('web_footer_body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='网站底部信息')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': '网站基本信息设置',
                'verbose_name': '网站基本信息设置',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='标签数量控制在四个以内', to='mysite.Tag', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mysite.Post', verbose_name='评论所属文章'),
        ),
    ]
